Add Child Policy Code to AWS Object Storage Optimization Policy
flexera-public/policy_templates pull request #1229
Opened 2023-04-05 14:07 UTC by XOmniverse

This just adds the additional code needed for this policy to work as a child policy.

Functionality as a regular policy is unchanged apart from the addition of a Flexera credential, since this is needed for the child policy functionality but was not present in the original policy.

The version is also bumped from 2.9 to 3.0, so even if the above is considered a "breaking change" (I imagine most customers have a Flexera credential at this point), the major version number also changed.

2023-04-07 16:22 UTC, bryankaraffa commented on cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
> +  version: "3.0",
This is a minor version change so would be `2.10`
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards compatible manner
https://semver.org/#summary

2023-04-07 16:27 UTC, bryankaraffa requested changes
Forgot the changes to the "first" datasource;
https://github.com/flexera-public/policy_templates/blob/POL-649/meta_policies/README_META_POLICIES.md#identify-first-datasource-and-add-header

2023-04-07 16:33 UTC, bryankaraffa requested changes
Also missing changes to `check` statement:
https://github.com/flexera-public/policy_templates/blob/POL-649/meta_policies/README_META_POLICIES.md#modify-policy-validation-check-statements

That [Meta Policy Development](https://github.com/flexera-public/policy_templates/blob/POL-649/meta_policies/README_META_POLICIES.md#meta-policy-development) Section in the README has all changes necessary for creating a net new Child and Meta Parent PT

2023-04-10 15:19 UTC, XOmniverse commented
All of the mentioned problems have been resolved:

* Version changed to 2.10
* Check statement modified
* Header added to first datasource that executes. I also moved this datasource to the top of the policy to avoid confusion.

2023-04-10 19:04 UTC, merged