POL-749 Add savings to AHUB policy
flexera-public/policy_templates pull request #1370
Opened 2023-07-21 17:08 UTC by mburmeig

### Description

[POL-794](https://flexera.atlassian.net/browse/POL-794)

### Issues Resolved

Added savings component to Azure hybrid usage benefit

### Link to Example Applied Policy

### Contribution Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2023-07-21 19:16 UTC, XOmniverse requested changes

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/README.md
> +- The savings currency is provided in $USD, and currency conversion is not supported.
We should add support for this. We now have an API capable of delivering this. See this policy: https://raw.githubusercontent.com/flexera-public/policy_templates/POL-832-aws-unused-ip-audit/cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt

Specifically ds_currency_target and the following datasources. You should be able to basically copypaste this into this policy and tweak it to match what this policy is doing.

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
> +  service: "compute",
compute should be capitalized to match other policies.

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
> +datasource "datasource_ds_azure_pricing" do
Datasource names should begin with ds_, not datasource_ds_. See:

https://flexera.atlassian.net/wiki/spaces/FP/pages/2184642622/Policy+Best+Practices#Block-Naming-Conventions

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
> +    var region_table = {
Add spaces between keys and values, like so: "ukwest": "UK West"

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
> +          monthlySavings = ((priceDifference * 24) * 30 )
To match parity with some changes we are making to our savings policies, the math here should be slightly different. Replace 30 with 365.25 / 12.

Reasoning: 365.25 is the average number of days in a year (due to a leap year every 4 years), so this gives us a much closer approximation of what the average monthly cost would be.

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
>  ##########
Datasources and Scripts should now be in a single combined section. I realize you didn't make it this way, but this is one of those things where, cuz you're touching the policy, it's yours now to fix :)

https://flexera.atlassian.net/wiki/spaces/FP/pages/2184642622/Policy+Best+Practices#Basic-Policy-Structure

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
> +  parameters "azure_instances","exclusion_tag", "pricing"
parameter variable names should be identical to their datasource or parameter counterparts when applicable. See: https://flexera.atlassian.net/wiki/spaces/FP/pages/2184642622/Policy+Best+Practices#Scripts

2023-07-21 19:16 UTC, XOmniverse commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
>        field "name" do
Incident output should have both subscription name and subscription id, and they should match accountname and accountid like our other policies to ensure the results are properly scraped. See the incident output section of this policy and try to include everything that would also make sense in this policy, with the same names:

https://raw.githubusercontent.com/flexera-public/policy_templates/master/cost/azure/old_snapshots/azure_delete_old_snapshots.pt

2023-08-07 15:13 UTC, XOmniverse requested changes
Here's my next set of recommendations. Let me know once these are in place.

2023-08-17 14:27 UTC, mburmeig commented on cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
>  # Datasources
Made recommended changes.

2023-09-18 12:19 UTC, XOmniverse approved these changes

2023-09-18 15:48 UTC, taterdog590 approved these changes
LGTM

2023-09-18 16:15 UTC, merged