FOPTS-1327 Turbonomic Rightsize Volumes (AWS)
flexera-public/policy_templates pull request #1392
Opened 2023-08-04 15:14 UTC by Rangelmv23

### Description

AWS Rightsize Volumes policy needs to show the following information: current and new storage access IOPs, current and new storage amount, VM volume is attached to, action nature: disruptive or not, reversible or not, current and new throughput capacity, IOPs utilization, disk utilization, throughput utilization, system details URL.

### Issues Resolved

Added all requested fields and normalized incident fields.

### Link to Example Applied Policy

- AWS Turbonomic Rightsize Volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64cc738acd41360001891c23

### Contribution Check List

- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

2023-08-04 15:45 UTC, vadgun requested changes

2023-08-04 15:45 UTC, vadgun commented on cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
> +      field "sizeUtilization" do
To be normalized according to excel normalization fields file, 
this Field can be renamed to : "newSizeUtil"

2023-08-04 15:45 UTC, vadgun commented on cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
> +        label "Current Size Utilization (%)"
"Current" word in all labels need to be removed, 
Change "Size" by "Storage" in all labels.
E.g. "Storage % Utilization"

2023-08-04 15:45 UTC, vadgun commented on cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
> +        label "Current Size Capacity (GB)"
Rename "Size" by "Storage"
Remove Current
Remove Capacity
E.g. "Storage (GB)"

2023-08-04 15:45 UTC, vadgun commented on cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
> +      end
****

2023-08-04 16:43 UTC, vadgun requested changes

2023-08-04 16:43 UTC, vadgun commented on cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
> +      end
****      field "throughput" do
        label "Throughput (MB/s)"
      end
      field "throughputP95" do
        label "Throughput % Utilization"
      end
      field "newThroughput" do
        label "New Throughput (MB/s)"
      end
      field "newThroughputP95" do
        label "New Throughput % Utilization"
      end

2023-08-07 17:20 UTC, vadgun reviewed
Looks good to me

2023-08-07 18:42 UTC, XOmniverse approved these changes
LGTM

2023-08-07 18:49 UTC, vadgun submitted a review, later dismissed
Looks Good to me

2023-08-07 23:05 UTC, night-codes approved these changes

2023-08-07 23:15 UTC, vadgun approved these changes
Looks good to me

2023-08-08 12:21 UTC, XOmniverse approved these changes
LGTM

2023-08-08 12:22 UTC, merged