FOPTS-1335 Turbonomic Rightsize DBs (GCP) - Bring recommendation supporting information
flexera-public/policy_templates pull request #1398
Opened 2023-08-11 09:15 UTC by vadgun

### Description

GCP Rightsize DBs policy needs to show the following information: VM age, uptime, vCPU capacity before/after, vCPU utilization before/after, Memory capacity before/after, memory utilization before/after, IOPs capacity and utilization before/after, disk capacity and utilization before/after, connection capacity and utilization before/after, system details URL.

### Issues Resolved

[FOPTS-1335](https://flexera.atlassian.net/browse/FOPTS-1335)

### Link to Example Applied Policy

[Turbonomic Rightsize Databases Recommendations GCP Policy Template Applied](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64d5f7ef53379b0001babd41)

### Contribution Check List

- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

2023-08-11 16:58 UTC, Rangelmv23 submitted a review, later dismissed
LGTM

2023-08-15 13:21 UTC, XOmniverse requested changes
Requested one small change to the CHANGELOG

2023-08-15 13:21 UTC, XOmniverse commented on cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
> +- Unpublished policy from catalog since Turbonomic Rightsize Database does not support Google provider yet.
I would remove this item since it doesn't really pertain to the functionality of the policy itself.

2023-08-21 19:13 UTC, Rangelmv23 submitted a review, later dismissed

2023-08-25 15:46 UTC, nia-vf1 commented on cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
>  ##################
```suggestion
###############################################################################
```

2023-08-25 15:47 UTC, nia-vf1 commented on cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
>  ##################
```suggestion
# Parameters
###############################################################################
```

2023-08-28 17:53 UTC, Rangelmv23 approved these changes

2023-08-29 20:46 UTC, night-codes approved these changes

2023-08-29 20:46 UTC, merged