FOPTS-1815 Low Account Usage Policy optimization
flexera-public/policy_templates pull request #1460
Opened 2023-09-13 23:42 UTC by Rangelmv23

### Description

The policy template can be optimized to reduce evaluation time. Currently there's a timeout happening.

### Issues Resolved

Policy template code is reviewed and optimized to improve performance.

### Link to Example Applied Policy

- Low Account Usage Policy: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=650245280105d50001c4d17e

### Contribution Check List

- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

2023-09-14 20:16 UTC, XOmniverse requested changes
This can probably be optimized further around line 206 by refactoring to avoid a nested loop. More info here: https://flexera.atlassian.net/wiki/spaces/FP/pages/2184773710/Policy+Optimization#Reduce-Looping-(Especially-Nested-Looping)

2023-09-14 23:32 UTC, Rangelmv23 commented
> This can probably be optimized further around line 206 by refactoring to avoid a nested loop. More info here: https://flexera.atlassian.net/wiki/spaces/FP/pages/2184773710/Policy+Optimization#Reduce-Looping-(Especially-Nested-Looping)

Hi, @XOmniverse . I tried using indexBy as the example in that documentation, but I got an error:
![image](https://github.com/flexera-public/policy_templates/assets/69998521/69ab3cde-3088-4757-9687-22f016e29029)

This is the code:
![image](https://github.com/flexera-public/policy_templates/assets/69998521/bb7a1e5b-5f4f-4fe9-b014-fe124e1e514d)

Could it be related to underscore version?

2023-09-18 18:15 UTC, midir99 approved these changes

2023-09-19 13:30 UTC, XOmniverse approved these changes
LGTM

2023-09-19 13:30 UTC, merged