feat: Added "Stop Instance" action for Idle resources
flexera-public/policy_templates pull request #1526
Opened 2023-10-06 22:17 UTC by bryankaraffa

### Description

Added "Stop Instance" action for Idle resources

### Link to Example Applied Policy

### Contribution Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [X] New functionality has been documented in CHANGELOG.MD

2023-10-09 12:20 UTC, XOmniverse requested changes
param_automatic_action should have a Stop Instances option.

It should match what is seen in other similar policies like this one, where the user can select stop OR delete as an automatic action: https://github.com/flexera-public/policy_templates/blob/master/cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt

2023-10-10 13:52 UTC, mburmeig approved these changes

2023-10-10 13:55 UTC, mburmeig submitted a review, later dismissed

2023-10-30 21:42 UTC, bryankaraffa commented
> param_automatic_action should have a Stop Instances option.
> 
> It should match what is seen in other similar policies like this one, where the user can select stop OR delete as an automatic action: https://github.com/flexera-public/policy_templates/blob/master/cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt

Fixed in https://github.com/flexera-public/policy_templates/pull/1526/files#diff-9e47704a4846c077cda93e9dcb2307747be5b1e38584b670213625def1b5248eR146

2023-10-31 20:18 UTC, merged