feat: Add params for github repo for Policy Sync PT
flexera-public/policy_templates pull request #1958
Opened 2024-03-25 21:19 UTC by bryankaraffa

### Description

Added parameters for the Policy Template Github Repo to enable this to be used for other repos without modifying Policy Template

### Link to Example Applied Policy

https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=6601da3c3ad5094c46961f0d

<img width="773" alt="image" src="https://github.com/flexera-public/policy_templates/assets/1490015/61b58be6-87c3-41cb-a968-b45f30849847">

Example overriding defaults to use data from a public repo (this is for a customer PoC):

https://github.com/bryankaraffa/friendly-engine

### Contribution Check List

- [X] New functionality includes testing.
- ~[ ] New functionality has been documented in the README if applicable~
- [X] New functionality has been documented in CHANGELOG.MD

2024-03-27 12:57 UTC, XOmniverse requested changes
Only one minor change requested.

2024-03-27 12:57 UTC, XOmniverse commented on tools/policy_sync/policy_sync.pt
> +short_description "This Policy Template can be used to synchronize (upload, overwrite, or alert) RS built-in policy templates in your account. See the [README](https://github.com/flexera-public/polic
References to RightScale, such as RS, should be removed.

2024-04-02 15:27 UTC, bryankaraffa commented
@XOmniverse -- if you have time for a re-review please and thank you !

2024-04-02 20:41 UTC, XOmniverse approved these changes
LGTM

2024-04-04 12:08 UTC, merged