FLFEX-5165 Add datalake optimization policy template
flexera-public/policy_templates pull request #2887
Opened 2024-12-13 21:39 UTC by midir99

### Description

### Issues Resolved

### Link to Example Applied Policy

### Contribution Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2024-12-17 19:17 UTC, XOmniverse requested changes

2024-12-17 20:53 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +  version: "1.0.0",
thanks @XOmniverse

2024-12-17 20:54 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +
thanks @XOmniverse, this change was addressed

2024-12-17 20:54 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +script "js_azure_distinct_regions", type: "javascript" do
thanks @XOmniverse, this change was addressed

2024-12-17 22:55 UTC, night-codes submitted a review, later dismissed

2024-12-18 16:04 UTC, XOmniverse requested changes
Requested a few more changes after reviewing again

2024-12-18 20:17 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +  label "Apply filtering for the Azure Data Lake Storage Accounts"
Hey @Shawn, thank you for the review, I changed this, let me know if new version is ok.

2024-12-18 20:17 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +  description "Apply filtering for the Azure Data Lake Storage Accounts where the hierarchical namespace is enabled"
Hey @Shawn, thank you for the review, I changed this, let me know if new version is ok.

2024-12-18 20:17 UTC, midir99 commented on cost/azure/data_lake_optimization/data_lake_optimization.pt
> +      if(account['hnsEnabled']){
Hey @Shawn, thank you for the review, I changed this, let me know if new version is ok.

2024-12-23 18:26 UTC, XOmniverse approved these changes
LGTM

2024-12-23 18:30 UTC, merged