POL-1431 - MSP Parent to Child Group Sync v0.1.0
flexera-public/policy_templates pull request #2893
Opened 2024-12-17 20:36 UTC by bryankaraffa

### Description

This policy template synchronizes groups, roles and users from a parent organization to child MSP organizations based on group description patterns. 

### Issues Resolved

https://flexera.atlassian.net/browse/POL-1432
https://flexera.atlassian.net/browse/FLEX-9110

### Link to Example Applied Policy

[Org 1105 > Applied Policies](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073)

### Contribution Check List

- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [X] New functionality has been documented in CHANGELOG.MD

2025-01-02 10:33 UTC, nia-vf1 commented on operational/flexera/msp_parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +short_description "Synchronizes user groups, membership, and permissions from MSP Parent org to user groups in MSP Child orgs"
```suggestion
short_description "This policy synchronizes user groups, membership, and permissions from MSP Parent org to user groups in MSP Child orgs. See the [README](https://github.com/flexera-public/policy_templates/tree/master/operational/flexera/msp_parent_child_group_sync/) and [docs.flexera.com/flexera/EN/Automation](https://docs.flexera.com/flexera/EN/Automation/AutomationGS.htm) to learn more."
```

2025-01-02 13:26 UTC, nia-vf1 commented on operational/flexera/msp_parent_child_group_sync/README.md
> +This policy template synchronizes groups, roles and users from a parent organization to child MSP organizations based on group description patterns. Groups in the parent org with descriptions matchin
Is there an example missing that should follow this paragraph?

2025-01-02 13:27 UTC, nia-vf1 commented on operational/flexera/msp_parent_child_group_sync/README.md
> +This policy template synchronizes groups, roles and users from a parent organization to child MSP organizations based on group description patterns. Groups in the parent org with descriptions matchin
Oh it is referring to line 9 onwards nvm

2025-01-02 13:28 UTC, nia-vf1 commented on operational/flexera/msp_parent_child_group_sync/README.md
> +OrgID can be a specific Child Org ID to sync the group with one specific child org, or `ALLORGS` to sync the group with all child orgs.
```suggestion
`<OrgID>` can be a specific Child Org ID to sync the group with one specific child org, or `ALLORGS` to sync the group with all child orgs.
```

2025-03-13 19:36 UTC, bryankaraffa commented
@flexera-public/policy-developers  -- ready for a merge on this whenever.  Customer has given their final 👍 .  Thanks in advance!

2025-03-27 17:57 UTC, XOmniverse requested changes

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +This policy template synchronizes groups, roles and users from a parent organization to child MSP organizations based on group description patterns. Groups in the parent org with descriptions matchin
Extra space here: "specified child org.  Using the"

Might be worth keeping the "What It Does" section fairly short and adding a "How It Works" section to cover the details, such as the pattern.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +The policy will:
Is this redundant with Policy Actions?

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +- Creates and updates groups in child orgs
Inconsistent casing on child org. Should either be "Child Org" or "child org" throughout the README.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +- Adds users if Child Org has Identity Provider, otherwise uses invitation flow to affiliate users to child orgs
Incorrect grammar. Comma should be a semicolon since this separates two complete sentences

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +- Removes roles and memberships that no longer exist in parent org
Whatever casing we land on for Child Org should also be used for Parent Org

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/README.md
> +- Must be deployed in an Org that has the `msp` capability enabled
This should probably be listed as a separate prerequisite outside of the "credentials" section.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +tenancy "single"
Outdated concept. "tenancy" statements should be removed since we're moving away from multiple projects anyway. It also always defaults to single if you have a credentials block regardless.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +  service: "IAM",
Currently inconsistent in existing policies (making a mental note to fix), but this should be expressed in full as "Identity & Access Management"

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +  policy_set: "MSP",
This should be policy_set: "Managed Service Provider" to match other policy templates.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +  description "Prefix to indicate the Group should be synced.  This is the first part of the string that needs to be in the description. **`<PrefixString>`**_`<ChildOrgID>`_`Child Group Name`"
Additional space not needed: "be synced.  This is the"

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +  description "Disable/Enable the invitation flow.  Users that can't be added directly to the Org due to missing required Identity Provider configuration will raise an error."
Additional space not needed: "ion flow.  Users that"

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +#### Begin Context
What does "Begin Context" mean?

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +  // Do not edit above this line
What is the purpose of this comment?

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +    _.each(ds_organizations, function(org) {
This could probably be replaced with a _.filter

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +      # field "description", jmes_path(col_item, "description")
Are these leftover debugging comments?

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +
Extra line break here should be removed.

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +
Extra line not needed

2025-03-27 17:57 UTC, XOmniverse commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +      # $child_role = http_request(
Is this old debug stuff that should be removed?

2025-04-16 15:52 UTC, bryankaraffa commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +    return (index % 4).toFixed(0);
TODO: Make number of batches a parameter

2025-04-22 19:28 UTC, bryankaraffa commented on operational/flexera/msp/parent_child_group_sync/flexera_msp_parent_child_group_sync.pt
> +
This is the start delimitor for the "context" incident, which can be used to hold state between run. This code between "Begin" (Line 140) + "End" Context comments (Line 230) is mostly reusable code that çan be copied and pasted into other PTs, and there's comments where to edit if needed.  This is a new capability, and we need to decide if it's something we want to re-use in other Policy Templates.  For now, it's needed in this one to maintain the batch index -- which batch number was last run.

2025-09-05 17:57 UTC, bryankaraffa commented
Closing this PR, we are approaching group sync for MSP use-cases with another method

2025-09-05 17:57 UTC, closed without merging