Google Cost Recommender: Added cost duration in months to incident output
flexera-public/policy_templates pull request #780
Opened 2021-11-10 15:49 UTC by XOmniverse

### Description

Added cost duration in months to incident output. Also removed the negative value from the cost in order to make the output more clear to the user.

Tested and confirmed it works as expected.

2021-11-10 17:55 UTC, cdwilhelm requested changes
Can we change cost to Monthly Savings, and include the currency symbol to the Monthly Savings like we do in other Policies.  Using a column for currency takes value away from more important columns.  Also the UI only shows the first 5 columns.  The most important columns should be showing first.

2021-11-10 20:00 UTC, XOmniverse commented
> Can we change cost to Monthly Savings, and include the currency symbol to the Monthly Savings like we do in other Policies. Using a column for currency takes value away from more important columns. Also the UI only shows the first 5 columns. The most important columns should be showing first.

I made most of these changes. I used "Savings" instead of "Monthly Savings" since it is not a given that it will always be for a single month. The column for "Savings Duration (Months)" should cover the amount of time.

2021-12-08 09:38 UTC, jez-chaplin approved these changes

2022-03-02 19:48 UTC, rshade commented
closing this as we are going to do a bunch of discrete policies.

2022-03-02 19:48 UTC, closed without merging