Pol 493
flexera-public/policy_templates pull request #851
Opened 2021-12-03 20:41 UTC by lawrethao

### Description

reduces iteration on shared scope to first item to provide more accurate recommended reserved instances.

### Issues Resolved

fixes shared subscription output showing too many duplicated recommendations

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2021-12-08 12:19 UTC, rshade requested changes

2021-12-08 12:19 UTC, rshade commented on cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
> +## v2.6
You need to bump the version in the policy also

2021-12-09 16:47 UTC, lawrethao reviewed
requested version changes have been commited

2021-12-09 16:50 UTC, rshade approved these changes
LGTM

2021-12-09 16:50 UTC, merged