Pol 501
flexera-public/policy_templates pull request #887
Opened 2022-01-11 16:57 UTC by lawrethao

### Description

Created a hard value policy based off of the recommender policy from google. Adds Google Committed use discount recommender hard policy for use

### Issues Resolved

fixes issue of recommender generic having separate outputs depending on recommender called. this will have output tailored to Google CUD recommender api response. 

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2022-01-12 15:41 UTC, rshade commented
@lawrethao check the error there seems to be a space in the folder name.

2022-01-13 16:17 UTC, rshade requested changes

2022-01-13 16:17 UTC, rshade commented on cost/google/cud_recommendations/README.md
> +- The `roles/recommender.cloudAssetInsightsViewer` role
Can you limit the roles to just what is needed for this policy?

2022-01-13 16:17 UTC, rshade commented on cost/google/cud_recommendations/google_cud_recommendations.pt
> +  description "Location to check, it can be the zone, region or global"
We might be able to remove this because cuds are only supported regionally. I think

2022-01-13 16:17 UTC, rshade commented on cost/google/cud_recommendations/google_cud_recommendations.pt
> +          location: location
We can modify this to the exact location of the CUDS

2022-01-14 14:56 UTC, rshade requested changes

2022-01-14 15:42 UTC, lawrethao commented on cost/google/cud_recommendations/google_cud_recommendations.pt
> +  default []
line has been removed.

2022-01-14 15:44 UTC, rshade approved these changes
LGTM

2022-01-25 16:49 UTC, merged