POL-560 Update SaaS Manager - Suspicious Users - email field and pagination fix
flexera-public/policy_templates pull request #907
Opened 2022-01-21 11:00 UTC by nia-vf1

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2022-01-25 14:28 UTC, rshade requested changes

2022-01-25 14:28 UTC, rshade commented on saas/fsm/suspicious_users/fsm-suspicious_users.pt
> +name "SaaS Manager - Suspicious Users (Nia testing)"
Need to fix this

2022-01-25 14:28 UTC, rshade commented on saas/fsm/suspicious_users/fsm-suspicious_users.pt
> +short_description "This policy will create an incident when Flexera SaaS Manager identifies suspicious users logging into SaaS applications. See the [README](https://github.com/flexera/policy_templat
Need to update this

2022-01-26 10:07 UTC, nia-vf1 commented on saas/fsm/suspicious_users/fsm-suspicious_users.pt
> +name "SaaS Manager - Suspicious Users (Nia testing)"
Done

2022-01-26 10:19 UTC, nia-vf1 commented on saas/fsm/suspicious_users/fsm-suspicious_users.pt
> +short_description "This policy will create an incident when Flexera SaaS Manager identifies suspicious users logging into SaaS applications. See the [README](https://github.com/flexera/policy_templat
Reverted it back to what it said before

2022-01-27 20:15 UTC, rshade approved these changes

2022-01-27 20:15 UTC, rshade commented
LGTM

2022-01-28 08:14 UTC, merged