Pol 554 AWS RI and Savings Plan Currency Adjustments
flexera-public/policy_templates pull request #916
Opened 2022-01-25 16:50 UTC by lawrethao

### Description

Adds currency parameter to aws instance and savings recommendations to multiply against monthly estimated savings

### Issues Resolved

fixes issue of not being able to convert savings into usable value

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2022-01-26 17:18 UTC, cdwilhelm requested changes
thanks for getting this done. some questions that may lead to change.

2022-01-28 15:44 UTC, lawrethao commented on cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
> +  min_value 0
I've removed the minimum value. do you know the use case? I couldn't think of when you'd have a currency that is a negative conversion number if value is based on a percentage against the USD.

2022-02-02 16:51 UTC, cdwilhelm approved these changes
LGTM

2022-02-02 16:53 UTC, merged

2022-02-02 21:44 UTC, douglaswth commented
@cdwilhelm / @lawrethao This PR only updated the version and not in the actual `info` metadata of the Policy Templates, so the new versions have not been published to the catalog.

2022-02-02 23:44 UTC, cdwilhelm commented
@douglaswth  thanks for catching this.  we'll get it fixed up