POL-584 Add AWS Savings Plan Utilization
flexera-public/policy_templates pull request #942
Opened 2022-03-17 13:54 UTC by nia-vf1

### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

2022-03-25 21:14 UTC, rshade requested changes

2022-03-28 10:23 UTC, nia-vf1 commented on cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
> +          chart_type: "cht=pd",
Done

2022-04-04 14:50 UTC, rshade approved these changes

2022-04-04 14:51 UTC, rshade commented
LGTM

2022-04-04 14:51 UTC, merged